language: python
env:

# apt-get is only available to the Ubuntu tests (os: linux)
# the other tests (os: osx) uses Homebrew to install shell
# dependencies and is done in ./utils/travis-install.sh
addons:
  apt:
    packages:
      - zsh
      - csh
      - tcsh
      - posh
      - ksh


git:
  depth: 100


cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log


python:
 - "2.7.10"
notifications:
 email: false
cache: pip
before_install:
  - export TZ=Europe/Prague
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
install:
  - git clone -b ng https://github.com/dtcooper/python-fitparse.git
  - cd python-fitparse
  - python setup.py install
  - cd ..
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels
  - python setup.py install
script:
 - nosetests tests/testparser.py
 - nosetests tests/test_rowingdata.py
sudo: required
after_success:
  - coveralls --config_file .coveragerc
